[package]
name = "mnomer"
version = "0.2.1"
authors = ["Thomas Frank <thfr.git@e.mail.de>"]
edition = "2021"

[[bin]]
name = "mnomer"

[lib]
name = "mnomer"

[dependencies]
cpal = "0.15.3"
crossterm = "0.28.1"
